blank_issues_enabled: false
contact_links:
  - name: Support Center
    url: https://github.com/nghoang1288/SSHBridge-Mobile/issues
    about: Report SSHBridge Mobile feature requests or bugs
  - name: Discord
    url: https://discord.gg/jVQGdvHDrf
    about: SSHBridge community chat for general discussion and quick support
